const fs = require("fs");
const path = require("path");

const legacy = [
  { src: "/images/4A9A7901.jpg", caption: "Rainforest Fern — Bwindi Impenetrable Forest", category: "nature", size: "medium" },
  { src: "/images/4A9A7902.jpg", caption: "Fern Fronds — Bwindi Forest", category: "nature", size: "tall" },
  { src: "/images/4A9A7964.jpg", caption: "Sabinyo Trail Head — Mgahinga Gorilla National Park", category: "adventure", size: "tall" },
  { src: "/images/4A9A7975.jpg", caption: "Forest Trail Trekking — Southwestern Uganda", category: "adventure", size: "medium" },
  { src: "/images/4A9A7977.jpg", caption: "Hiker on Moss-Covered Rock — Bwindi Region", category: "adventure", size: "medium" },
  { src: "/images/4A9A7980.jpg", caption: "Forest Trekking — Bwindi Region", category: "adventure", size: "tall" },
  { src: "/images/4A9A7987.jpg", caption: "Rest Stop in the Rainforest — Bwindi", category: "adventure", size: "medium" },
  { src: "/images/4A9A8026.jpg", caption: "Ancient Tree — Forest Trek", category: "nature", size: "medium" },
  { src: "/images/4A9A8221.jpg", caption: "Traditional Dance Performance — Uganda", category: "culture", size: "wide" },
  { src: "/images/4A9A8222.jpg", caption: "Drumming and Dance — Uganda", category: "culture", size: "wide" },
  { src: "/images/4A9A8403.jpg", caption: "Safari Vehicle Crossing — Mountain Route", category: "adventure", size: "tall" },
  { src: "/images/4A9A8457.jpg", caption: "Guided Forest Trek — Southwestern Uganda", category: "adventure", size: "wide" },
  { src: "/images/4A9A8545.jpg", caption: "Moss-Covered Forest — Bwindi Region", category: "nature", size: "tall" },
  { src: "/images/4A9A8560.jpg", caption: "Primeval Forest Canopy — Uganda Highlands", category: "nature", size: "tall" },
  { src: "/images/4A9A8563.jpg", caption: "Sunlit Moss and Ferns — Rainforest", category: "nature", size: "medium" },
  { src: "/images/4A9A8590.jpg", caption: "Mountain Gorilla — Bwindi Impenetrable Forest", category: "wildlife", size: "large" },
  { src: "/images/4A9A8591.jpg", caption: "Mountain Gorilla Foraging — Bwindi", category: "wildlife", size: "medium" },
  { src: "/images/4A9A8592.jpg", caption: "Mountain Gorilla — Bwindi Rainforest", category: "wildlife", size: "medium" },
  { src: "/images/4A9A8600.jpg", caption: "Young Mountain Gorilla — Bwindi", category: "wildlife", size: "tall" },
  { src: "/images/4A9A8602.jpg", caption: "Silverback Gorilla — Bwindi Impenetrable Forest", category: "wildlife", size: "tall" },
  { src: "/images/4A9A8603.jpg", caption: "Mountain Gorilla Resting — Bwindi", category: "wildlife", size: "medium" },
  { src: "/images/4A9A8605.jpg", caption: "Silverback Gorilla — Bwindi Forest", category: "wildlife", size: "medium" },
  { src: "/images/4A9A8610.jpg", caption: "Mountain Gorilla Profile — Bwindi", category: "wildlife", size: "medium" },
  { src: "/images/4A9A8612.jpg", caption: "Mountain Gorilla — Bwindi Impenetrable Forest", category: "wildlife", size: "tall" },
  { src: "/images/4A9A8620.jpg", caption: "Mountain Gorilla at Rest — Bwindi", category: "wildlife", size: "medium" },
  { src: "/images/4A9A8626.jpg", caption: "Mountain Gorilla — Bwindi Rainforest", category: "wildlife", size: "medium" },
  { src: "/images/4A9A8634.jpg", caption: "Silverback Gorilla — Bwindi", category: "wildlife", size: "medium" },
  { src: "/images/4A9A0445.jpg", caption: "Elephant Herd at River — Murchison Falls", category: "wildlife", size: "large" },
  { src: "/images/4A9A0449.jpg", caption: "Elephant Herd at Riverbank — Uganda", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0451.jpg", caption: "Elephants at the Nile — Murchison Falls", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0453.jpg", caption: "Elephants at River — Uganda Savanna", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0455.jpg", caption: "Elephants Drinking — River Safari", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0458.jpg", caption: "Elephants at the Water's Edge — Uganda", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0460.jpg", caption: "Hippo in the Nile — Murchison Falls", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0462.jpg", caption: "Elephants Drinking — Riverbank", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0463.jpg", caption: "Elephant at River — Uganda", category: "wildlife", size: "medium" },
  { src: "/images/4A9A0474.jpg", caption: "Elephant Herd — Savanna", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0483.jpg", caption: "Elephant Herd — Queen Elizabeth Region", category: "wildlife", size: "wide" },
  { src: "/images/4A9A0486.jpg", caption: "Elephant Family With Calves — Savanna", category: "wildlife", size: "wide" },
  { src: "/images/4A9A9703.jpg", caption: "African Wattled Lapwing — Queen Elizabeth", category: "wildlife", size: "medium" },
  { src: "/images/4A9A9707.jpg", caption: "White-Backed Vultures — Acacia Tree", category: "wildlife", size: "wide" },
  { src: "/images/4A9A9709.jpg", caption: "White-Backed Vulture — Savanna", category: "wildlife", size: "tall" },
  { src: "/images/4A9A9717.jpg", caption: "White-Backed Vulture — Acacia Savanna", category: "wildlife", size: "tall" },
  { src: "/images/4A9A9719.jpg", caption: "White-Backed Vulture — Thorn Tree", category: "wildlife", size: "medium" },
  { src: "/images/4A9A9726.jpg", caption: "Vulture Perched — Savanna Sky", category: "wildlife", size: "tall" },
  { src: "/images/4A9A9731.jpg", caption: "African Wattled Lapwing — Dry Grassland", category: "wildlife", size: "wide" },
];

const newImages = [
  { src: "/images/IMG-20260811-WA0012.jpg", caption: "Nakupenda Sandbank — Zanzibar", category: "adventure", size: "tall" },
  { src: "/images/IMG-20260811-WA0013.jpg", caption: "Vervet Monkey — Zanzibar Forest", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0014.jpg", caption: "White Rhino and Cattle Egret — East Africa", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0015.jpg", caption: "Snorkeling Excursion — Mnemba Atoll", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0016.jpg", caption: "The Rock Restaurant — Michamvi, Zanzibar", category: "luxury", size: "medium" },
  { src: "/images/IMG-20260811-WA0017.jpg", caption: "Prison Island — Zanzibar", category: "nature", size: "medium" },
  { src: "/images/IMG-20260811-WA0018.jpg", caption: "Clear Kayak — Zanzibar", category: "luxury", size: "tall" },
  { src: "/images/IMG-20260811-WA0019.jpg", caption: "Aldabra Giant Tortoise — Prison Island", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0020.jpg", caption: "Coke's Hartebeest — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0021.jpg", caption: "Lion and Lioness — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0022.jpg", caption: "Safari Blue Dhow — Zanzibar", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0023.jpg", caption: "Cave Pool Snorkeling — Zanzibar", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0024.jpg", caption: "Zanzibar Red Colobus — Jozani Forest", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0025.jpg", caption: "Safari Vehicle and Giraffe — Serengeti", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0026.jpg", caption: "Masai Giraffe — East African Savanna", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0027.jpg", caption: "Warthog and Piglet — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0028.jpg", caption: "Pristine Sandbank — Zanzibar Coast", category: "nature", size: "medium" },
  { src: "/images/IMG-20260811-WA0029.jpg", caption: "Yawning Lioness — Masai Mara", category: "wildlife", size: "wide" },
  { src: "/images/IMG-20260811-WA0030.jpg", caption: "Aldabra Giant Tortoise — Prison Island", category: "wildlife", size: "tall" },
  { src: "/images/IMG-20260811-WA0031.jpg", caption: "Bottlenose Dolphins — Indian Ocean", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0032.jpg", caption: "Prison Island Aerial — Zanzibar", category: "nature", size: "tall" },
  { src: "/images/IMG-20260811-WA0033.jpg", caption: "Sandbank Solitude — Zanzibar", category: "luxury", size: "medium" },
  { src: "/images/IMG-20260811-WA0034.jpg", caption: "African Elephants and Kilimanjaro — Amboseli", category: "wildlife", size: "large" },
  { src: "/images/IMG-20260811-WA0035.jpg", caption: "Masai Giraffe and Calf — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0036.jpg", caption: "Cave Pool — Kitum Cave", category: "nature", size: "tall" },
  { src: "/images/IMG-20260811-WA0037.jpg", caption: "Sandbank Excursion — Nakupenda Beach", category: "adventure", size: "medium" },
  { src: "/images/IMG-20260811-WA0038.jpg", caption: "Lion Pride — Masai Mara", category: "wildlife", size: "wide" },
  { src: "/images/IMG-20260811-WA0039.jpg", caption: "Pristine Sandbank — Zanzibar", category: "adventure", size: "medium" },
  { src: "/images/IMG-20260811-WA0040.jpg", caption: "Male Lion — Ngorongoro Crater", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0041.jpg", caption: "Cape Buffalo — East African Savanna", category: "wildlife", size: "tall" },
  { src: "/images/IMG-20260811-WA0042.jpg", caption: "Aldabra Giant Tortoises — Prison Island", category: "wildlife", size: "large" },
  { src: "/images/IMG-20260811-WA0043.jpg", caption: "Coastal Dhows — Zanzibar", category: "adventure", size: "tall" },
  { src: "/images/IMG-20260811-WA0045.jpg", caption: "Coastal Boat Trip — Zanzibar", category: "adventure", size: "tall" },
  { src: "/images/IMG-20260811-WA0046.jpg", caption: "Mating Lions — Serengeti", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0047.jpg", caption: "Spice Farm Welcome — Zanzibar", category: "culture", size: "tall" },
  { src: "/images/IMG-20260811-WA0048.jpg", caption: "Giant Tortoise Encounter — Changuu Island", category: "wildlife", size: "tall" },
  { src: "/images/IMG-20260811-WA0049.jpg", caption: "Grilled Seafood Feast — Zanzibar", category: "luxury", size: "medium" },
  { src: "/images/IMG-20260811-WA0050.jpg", caption: "African Wild Dog — Serengeti", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0051.jpg", caption: "White-Backed Vulture — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0052.jpg", caption: "Beisa Oryx Sparring — Samburu", category: "wildlife", size: "wide" },
  { src: "/images/IMG-20260811-WA0053.jpg", caption: "Ostrich Herd — Ngorongoro Crater", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0054.jpg", caption: "Lioness With Kill — Serengeti", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0055.jpg", caption: "Rocky Island — Zanzibar", category: "nature", size: "medium" },
  { src: "/images/IMG-20260811-WA0056.jpg", caption: "Jackfruit Tree — Zanzibar Spice Farm", category: "culture", size: "medium" },
  { src: "/images/IMG-20260811-WA0057.jpg", caption: "Mnemba Island — Zanzibar", category: "nature", size: "tall" },
  { src: "/images/IMG-20260811-WA0058.jpg", caption: "Dhow Under Sail — Zanzibar", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0059.jpg", caption: "Safari Blue Lagoon — Zanzibar", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0060.jpg", caption: "Dolphin Pod — Zanzibar Coast", category: "wildlife", size: "tall" },
  { src: "/images/IMG-20260811-WA0061.jpg", caption: "Masai Giraffe — Masai Mara", category: "wildlife", size: "wide" },
  { src: "/images/IMG-20260811-WA0062.jpg", caption: "Masai Giraffe and Calf — Serengeti", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0063.jpg", caption: "Sykes' Monkey — Jozani Forest", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0064.jpg", caption: "Sandbank Excursion — Zanzibar", category: "adventure", size: "medium" },
  { src: "/images/IMG-20260811-WA0065.jpg", caption: "Green Sea Turtles — Nungwi", category: "adventure", size: "medium" },
  { src: "/images/IMG-20260811-WA0066.jpg", caption: "Dolphin Pod Swim — Zanzibar Coast", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0067.jpg", caption: "Traditional Dhow — Zanzibar Coast", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0068.jpg", caption: "Common Warthog — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0069.jpg", caption: "African Elephant — Masai Mara", category: "wildlife", size: "large" },
  { src: "/images/IMG-20260811-WA0070.jpg", caption: "Green Sea Turtles — Nungwi", category: "adventure", size: "tall" },
  { src: "/images/IMG-20260811-WA0071.jpg", caption: "Young Male Lion — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0072.jpg", caption: "Peregrine Falcon — East Africa", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0073.jpg", caption: "Masai Giraffe — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0074.jpg", caption: "Lion Pair — Masai Mara", category: "wildlife", size: "large" },
  { src: "/images/IMG-20260811-WA0075.jpg", caption: "Prison Island — Zanzibar", category: "nature", size: "medium" },
  { src: "/images/IMG-20260811-WA0076.jpg", caption: "Prison Island Resort — Changuu Island", category: "luxury", size: "medium" },
  { src: "/images/IMG-20260811-WA0077.jpg", caption: "Dolphins Leaping — Zanzibar Coast", category: "adventure", size: "medium" },
  { src: "/images/IMG-20260811-WA0078.jpg", caption: "Palm Weaving Workshop — Zanzibar", category: "culture", size: "medium" },
  { src: "/images/IMG-20260811-WA0079.jpg", caption: "Elephant Herd — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0080.jpg", caption: "Nakupenda Sandbank — Zanzibar", category: "adventure", size: "wide" },
  { src: "/images/IMG-20260811-WA0081.jpg", caption: "Greater Kudu — East Africa", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0083.jpg", caption: "Zanzibar Red Colobus — Jozani Forest", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0084.jpg", caption: "Palm Weaving Experience — Zanzibar", category: "culture", size: "tall" },
  { src: "/images/IMG-20260811-WA0085.jpg", caption: "Nile Crocodile — East Africa", category: "wildlife", size: "tall" },
  { src: "/images/IMG-20260811-WA0086.jpg", caption: "Cape Buffalo — East African Savanna", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0087.jpg", caption: "African Elephant — East African Savanna", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0088.jpg", caption: "Spice Tour — Zanzibar", category: "culture", size: "tall" },
  { src: "/images/IMG-20260811-WA0089.jpg", caption: "The Rock Restaurant — Zanzibar", category: "luxury", size: "tall" },
  { src: "/images/IMG-20260811-WA0090.jpg", caption: "Luxury Dhow Cruise — Zanzibar", category: "luxury", size: "tall" },
  { src: "/images/IMG-20260811-WA0091.jpg", caption: "Achiote Seeds — Zanzibar Spice Farm", category: "culture", size: "medium" },
  { src: "/images/IMG-20260811-WA0092.jpg", caption: "Giant Tortoise — Prison Island", category: "wildlife", size: "tall" },
  { src: "/images/IMG-20260811-WA0093.jpg", caption: "Grilled Seafood Platter — Zanzibar Coast", category: "luxury", size: "medium" },
  { src: "/images/IMG-20260811-WA0094.jpg", caption: "Stone Town Waterfront — Zanzibar", category: "culture", size: "wide" },
  { src: "/images/IMG-20260811-WA0096.jpg", caption: "Red Colobus Monkey — Jozani Forest", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0097.jpg", caption: "Mnemba Island — Zanzibar", category: "nature", size: "large" },
  { src: "/images/IMG-20260811-WA0098.jpg", caption: "Masai Giraffe and Calf — Masai Mara", category: "wildlife", size: "medium" },
  { src: "/images/IMG-20260811-WA0099.jpg", caption: "Hippopotamus — East Africa", category: "wildlife", size: "tall" },
];

const items = [...legacy, ...newImages].map((item, i) => ({
  id: `g${i + 1}`,
  ...item,
}));

function formatItem(item) {
  return `  { id: "${item.id}", src: "${item.src}", caption: "${item.caption}", category: "${item.category}", size: "${item.size}" }`;
}

const body = [
  "export type GalleryItem = {",
  "  id: string;",
  "  src: string;",
  "  caption: string;",
  "  category: string;",
  '  size: "small" | "medium" | "large" | "wide" | "tall";',
  "};",
  "",
  "export const galleryItems: GalleryItem[] = [",
  items.map(formatItem).join(",\n"),
  "];",
  "",
  "export const galleryCategories = [",
  '  { id: "all", label: "All" },',
  '  { id: "wildlife", label: "Wildlife" },',
  '  { id: "nature", label: "Nature" },',
  '  { id: "adventure", label: "Adventure" },',
  '  { id: "culture", label: "Culture" },',
  '  { id: "luxury", label: "Luxury" },',
  "];",
  "",
].join("\n");

fs.writeFileSync(path.join(__dirname, "..", "src", "data", "gallery.ts"), body);
console.log(`Wrote ${items.length} gallery items`);
